# Dockerfile.ollama

FROM ollama/ollama:latest

# Install wget
RUN apt-get update && apt-get install -y wget

# Copy and set permissions for the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
