version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama_container
    networks:
      - my_network
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: my-streamlit
    networks:
      - my_network
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate

volumes:
  ollama_data:

networks:
  my_network:
    driver: bridge
